export const gameData = {
    apiKeys: [
        "AIzaSyB5raGlKb5kw9Rlag0CNJQeVcF17XBrdk8", // Pega aquí tu primera API Key
        "AIzaSyA7byKbrGETHW7Vn_IA7ACUeJJ3H0NU-8c", // Opcional: tu segunda API Key
        "AIzaSyBb3Fx3KTxL2KHtijQHpGMUQfLrXyJT9_k"  // Opcional: tu tercera API Key
    ],
    modelFallbackOrder: [
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite"
    ],
    races: [
        'aguila',
        'aranya',
        'arpia',
        'ave',
        'burro',
        'caballo',
        'centauro',
        'cerdo',
        'ciempies',
        'ciervo',
        'cocodrilo',
        'conejo',
        'demon',
        'draconiano',
        'dragon',
        'drow',
        'elefantino',
        'element',
        'elfo',
        'elian-lal',
        'enano',
        'ent',
        'esqueleto',
        'felino',
        'fido',
        'gallina',
        'gallina acuatica',
        'gargola',
        'gato',
        'gigante',
        'gnomo',
        'goblin',
        'gorkr-ror',
        'grifo',
        'hobbit',
        'hobgoblin',
        'humano',
        'insecto',
        'kobold',
        'lagarto',
        'lobo',
        'mamifero',
        'modron',
        'monstruo escuela',
        'murcielago',
        'orco',
        'oso',
        'pajarito',
        'pegaso',
        'perro',
        'pez',
        'planta',
        'rata',
        'raton',
        'sentientobject',
        'serpiente',
        'slime',
        'troll',
        'unicornio',
        'unique',
        'vampiro',
        'wyvern',
        'zombie',
        'zorro'
    ]
    // Aquí se pueden añadir futuras listas (materiales, tipos de armas, etc.)
};
