export const gameData = {
    apiKeys: [
        "AIzaSyB5raGlKb5kw9Rlag0CNJQeVcF17XBrdk8", // Pega aquí tu primera API Key
        "AIzaSyA7byKbrGETHW7Vn_IA7ACUeJJ3H0NU-8c", // Opcional: tu segunda API Key
        "AIzaSyBb3Fx3KTxL2KHtijQHpGMUQfLrXyJT9_k"  // Opcional: tu tercera API Key
    ],
    modelFallbackOrder: [
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite"
    ],
    races: [
        'aguila',
        'aranya',
        'arpia',
        'ave',
        'burro',
        'caballo',
        'centauro',
        'cerdo',
        'ciempies',
        'ciervo',
        'cocodrilo',
        'conejo',
        'demon',
        'draconiano',
        'dragon',
        'drow',
        'elefantino',
        'element',
        'elfo',
        'elian-lal',
        'enano',
        'ent',
        'esqueleto',
        'felino',
        'fido',
        'gallina',
        'gallina acuatica',
        'gargola',
        'gato',
        'gigante',
        'gnomo',
        'goblin',
        'gorkr-ror',
        'grifo',
        'hobbit',
        'hobgoblin',
        'humano',
        'insecto',
        'kobold',
        'lagarto',
        'lobo',
        'mamifero',
        'modron',
        'monstruo escuela',
        'murcielago',
        'orco',
        'oso',
        'pajarito',
        'pegaso',
        'perro',
        'pez',
        'planta',
        'rata',
        'raton',
        'sentientobject',
        'serpiente',
        'slime',
        'troll',
        'unicornio',
        'unique',
        'vampiro',
        'wyvern',
        'zombie',
        'zorro'
    ],
    damageTypes: [
        { value: 'slice', description: 'tajo' },
        { value: 'stab', description: 'pinchazo' },
        { value: 'slash', description: 'golpe de espada' },
        { value: 'latigo', description: 'latigazo' },
        { value: 'claw', description: 'gancho' },
        { value: 'blast', description: 'mazazo' },
        { value: 'pound', description: 'porrazo' },
        { value: 'crush', description: 'cabezazo' },
        { value: 'grep', description: 'estoque' },
        { value: 'bite', description: 'mordisco' },
        { value: 'pierce', description: 'estoque' },
        { value: 'suction', description: 'succionamiento letal' },
        { value: 'beating', description: 'azote' },
        { value: 'digestion', description: 'vomito acido' },
        { value: 'charge', description: 'barrigazo' },
        { value: 'slap', description: 'bofetón' },
        { value: 'punch', description: 'punch' },
        { value: 'wrath', description: 'golpe furioso' },
        { value: 'magic', description: 'mágico pase' },
        { value: 'divine', description: 'poder divino' },
        { value: 'cleave', description: 'golpe carnicero' },
        { value: 'scratch', description: 'zarcalmao ursido' },
        { value: 'peck', description: 'picotazo' },
        { value: 'peckb', description: 'besito de hierro' },
        { value: 'chop', description: 'tajo devastador' },
        { value: 'sting', description: 'ataque \'picadura de avispa\'' },
        { value: 'smash', description: 'choque' },
        { value: 'shbite', description: 'relámpago luminoso' },
        { value: 'flbite', description: 'chorro de fuego' },
        { value: 'frbite', description: 'golpe helador' },
        { value: 'acbite', description: 'golpe ácido' },
        { value: 'chomp', description: 'chomp' },
        { value: 'drain', description: 'pase de succión vital' },
        { value: 'thrust', description: 'empujón' },
        { value: 'slime', description: 'salivazo' },
        { value: 'shock', description: 'shock' },
        { value: 'thwack', description: 'Plaff!' },
        { value: 'flame', description: 'llamarazo' },
        { value: 'chill', description: 'pinchazo frío' }
    ],
    hitrollRecommendations: [
        { levelStart: 1, levelEnd: 20, hitrollMin: 0, hitrollMax: 5 },
        { levelStart: 21, levelEnd: 40, hitrollMin: 7, hitrollMax: 20 },
        { levelStart: 41, levelEnd: 60, hitrollMin: 25, hitrollMax: 45 },
        { levelStart: 61, levelEnd: 80, hitrollMin: 50, hitrollMax: 75 },
        { levelStart: 81, levelEnd: 100, hitrollMin: 80, hitrollMax: 100 },
        { levelStart: 101, levelEnd: 120, hitrollMin: 115, hitrollMax: 150 }
    ]
    // Aquí se pueden añadir futuras listas (materiales, tipos de armas, etc.)
};
