const affectIRVBits = [
    { value: 'A', label: 'Summon' },
    { value: 'B', label: 'Charm' },
    { value: 'C', label: 'Magic' },
    { value: 'D', label: 'Weapons' },
    { value: 'E', label: 'Bash' },
    { value: 'F', label: 'Pierce' },
    { value: 'G', label: 'Slash' },
    { value: 'H', label: 'Fire' },
    { value: 'I', label: 'Cold' },
    { value: 'J', label: 'Lightning' },
    { value: 'K', label: 'Acid' },
    { value: 'L', label: 'Poison' },
    { value: 'M', label: 'Negative' },
    { value: 'N', label: 'Holy' },
    { value: 'O', label: 'Energy' },
    { value: 'P', label: 'Mental' },
    { value: 'Q', label: 'Disease' },
    { value: 'R', label: 'Drowning' },
    { value: 'S', label: 'Light' },
    { value: 'T', label: 'Sound' },
    { value: 'X', label: 'Wood' },
    { value: 'Y', label: 'Silver' },
    { value: 'Z', label: 'Iron' }
];

export const gameData = {
    // Configuración de las API Keys para los modelos de IA de Gemini.
    // Se pueden añadir múltiples keys para rotación o fallback.
    apiKeys: [
        "AIzaSyB5raGlKb5kw9Rlag0CNJQeVcF17XBrdk8", // Pega aquí tu primera API Key
        "AIzaSyA7byKbrGETHW7Vn_IA7ACUeJJ3H0NU-8c", // Opcional: tu segunda API Key
        "AIzaSyBb3Fx3KTxL2KHtijQHpGMUQfLrXyJT9_k"  // Opcional: tu tercera API Key
    ],
    // Define el orden de preferencia de los modelos de IA a utilizar.
    // La aplicación intentará usar los modelos en este orden hasta encontrar uno disponible o exitoso.
    modelFallbackOrder: [
        "gemini-2.5-pro",
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite"
    ],
    // Lista de razas disponibles para los mobs en el juego.
    // Utilizada para poblar los selectores de raza en la interfaz de usuario.
    races: [
        'aguila',
        'aranya',
        'arpia',
        'ave',
        'burro',
        'caballo',
        'centauro',
        'cerdo',
        'ciempies',
        'ciervo',
        'cocodrilo',
        'conejo',
        'demon',
        'draconiano',
        'dragon',
        'drow',
        'elefantino',
        'element',
        'elfo',
        'elian-lal',
        'enano',
        'ent',
        'esqueleto',
        'felino',
        'fido',
        'gallina',
        'gallina acuatica',
        'gargola',
        'gato',
        'gigante',
        'gnomo',
        'goblin',
        'gorkr-ror',
        'grifo',
        'hobbit',
        'hobgoblin',
        'humano',
        'insecto',
        'kobold',
        'lagarto',
        'lobo',
        'mamifero',
        'modron',
        'monstruo escuela',
        'murcielago',
        'orco',
        'oso',
        'pajarito',
        'pegaso',
        'perro',
        'pez',
        'planta',
        'rata',
        'raton',
        'sentientobject',
        'serpiente',
        'slime',
        'troll',
        'unicornio',
        'unique',
        'vampiro',
        'wyvern',
        'zombie',
        'zorro'
    ],
    // Tipos de daño que pueden infligir los mobs o las armas.
    // Cada entrada tiene un 'value' (para uso interno) y una 'description' (para mostrar en la UI).
    damageTypes: [
        { value: 'none', description: 'nada' },
        { value: 'slice', description: 'tajo' },
        { value: 'stab', description: 'pinchazo' },
        { value: 'slash', description: 'golpe de espada' },
        { value: 'latigo', description: 'latigazo' },
        { value: 'claw', description: 'gancho' },
        { value: 'blast', description: 'mazazo' },
        { value: 'pound', description: 'porrazo' },
        { value: 'crush', description: 'cabezazo' },
        { value: 'grep', description: 'estoque' },
        { value: 'bite', description: 'mordisco' },
        { value: 'pierce', description: 'estoque' },
        { value: 'suction', description: 'succionamiento letal' },
        { value: 'beating', description: 'azote' },
        { value: 'digestion', description: 'vomito acido' },
        { value: 'charge', description: 'barrigazo' },
        { value: 'slap', description: 'bofetón' },
        { value: 'punch', description: 'punch' },
        { value: 'wrath', description: 'golpe furioso' },
        { value: 'magic', description: 'mágico pase' },
        { value: 'divine', description: 'poder divino' },
        { value: 'cleave', description: 'golpe carnicero' },
        { value: 'scratch', description: 'zarcalmao ursido' },
        { value: 'peck', description: 'picotazo' },
        { value: 'peckb', description: 'besito de hierro' },
        { value: 'chop', description: 'tajo devastador' },
        { value: 'sting', description: 'ataque \'picadura de avispa\'' },
        { value: 'smash', description: 'choque' },
        { value: 'shbite', description: 'relámpago luminoso' },
        { value: 'flbite', description: 'chorro de fuego' },
        { value: 'frbite', description: 'golpe helador' },
        { value: 'acbite', description: 'golpe ácido' },
        { value: 'chomp', description: 'chomp' },
        { value: 'drain', description: 'pase de succión vital' },
        { value: 'thrust', description: 'empujón' },
        { value: 'slime', description: 'salivazo' },
        { value: 'shock', description: 'shock' },
        { value: 'thwack', description: 'Plaff!' },
        { value: 'flame', description: 'llamarazo' },
        { value: 'chill', description: 'pinchazo frío' }
    ],
    // Recomendaciones de 'hitroll' para mobs, basadas en rangos de nivel.
    // Utilizado para el auto-rellenado de estadísticas de mobs.
    hitrollRecommendations: [
        { levelStart: 1, levelEnd: 20, hitrollMin: 0, hitrollMax: 5 },
        { levelStart: 21, levelEnd: 40, hitrollMin: 7, hitrollMax: 20 },
        { levelStart: 41, levelEnd: 60, hitrollMin: 25, hitrollMax: 45 },
        { levelStart: 61, levelEnd: 80, hitrollMin: 50, hitrollMax: 75 },
        { levelStart: 81, levelEnd: 100, hitrollMin: 80, hitrollMax: 100 },
        { levelStart: 101, levelEnd: 120, hitrollMin: 115, hitrollMax: 150 }
    ],
    // Recomendaciones de estadísticas (HP, Mana, Armadura, Daño) para mobs por nivel.
    // Utilizado para el auto-rellenado de estadísticas de mobs.
    mobStatsRecommendations: [
        { level: 1, hpManaDice: { num: 2, sides: 6, bonus: 10 }, armor: 9, damageDice: { num: 1, sides: 4, bonus: 0 } },
        { level: 2, hpManaDice: { num: 2, sides: 7, bonus: 21 }, armor: 8, damageDice: { num: 1, sides: 5, bonus: 0 } },
        { level: 3, hpManaDice: { num: 2, sides: 6, bonus: 35 }, armor: 7, damageDice: { num: 1, sides: 6, bonus: 0 } },
        { level: 4, hpManaDice: { num: 2, sides: 7, bonus: 46 }, armor: 6, damageDice: { num: 1, sides: 5, bonus: 1 } },
        { level: 5, hpManaDice: { num: 2, sides: 6, bonus: 60 }, armor: 5, damageDice: { num: 1, sides: 6, bonus: 1 } },
        { level: 6, hpManaDice: { num: 2, sides: 7, bonus: 71 }, armor: 4, damageDice: { num: 1, sides: 7, bonus: 1 } },
        { level: 7, hpManaDice: { num: 2, sides: 6, bonus: 85 }, armor: 4, damageDice: { num: 1, sides: 8, bonus: 1 } },
        { level: 8, hpManaDice: { num: 2, sides: 7, bonus: 96 }, armor: 3, damageDice: { num: 1, sides: 7, bonus: 2 } },
        { level: 9, hpManaDice: { num: 2, sides: 6, bonus: 110 }, armor: 2, damageDice: { num: 1, sides: 8, bonus: 2 } },
        { level: 10, hpManaDice: { num: 2, sides: 7, bonus: 121 }, armor: 1, damageDice: { num: 2, sides: 4, bonus: 2 } },
        { level: 11, hpManaDice: { num: 2, sides: 8, bonus: 134 }, armor: 1, damageDice: { num: 1, sides: 10, bonus: 2 } },
        { level: 12, hpManaDice: { num: 2, sides: 10, bonus: 150 }, armor: 0, damageDice: { num: 1, sides: 10, bonus: 3 } },
        { level: 13, hpManaDice: { num: 2, sides: 10, bonus: 170 }, armor: -1, damageDice: { num: 2, sides: 5, bonus: 3 } },
        { level: 14, hpManaDice: { num: 2, sides: 10, bonus: 190 }, armor: -1, damageDice: { num: 1, sides: 12, bonus: 3 } },
        { level: 15, hpManaDice: { num: 3, sides: 9, bonus: 208 }, armor: -2, damageDice: { num: 2, sides: 6, bonus: 3 } },
        { level: 16, hpManaDice: { num: 3, sides: 9, bonus: 233 }, armor: -2, damageDice: { num: 2, sides: 6, bonus: 4 } },
        { level: 17, hpManaDice: { num: 3, sides: 9, bonus: 258 }, armor: -3, damageDice: { num: 3, sides: 4, bonus: 4 } },
        { level: 18, hpManaDice: { num: 3, sides: 9, bonus: 283 }, armor: -3, damageDice: { num: 2, sides: 7, bonus: 4 } },
        { level: 19, hpManaDice: { num: 3, sides: 9, bonus: 308 }, armor: -4, damageDice: { num: 2, sides: 7, bonus: 5 } },
        { level: 20, hpManaDice: { num: 3, sides: 9, bonus: 333 }, armor: -4, damageDice: { num: 2, sides: 8, bonus: 5 } },
        { level: 21, hpManaDice: { num: 4, sides: 10, bonus: 360 }, armor: -5, damageDice: { num: 4, sides: 4, bonus: 5 } },
        { level: 22, hpManaDice: { num: 5, sides: 10, bonus: 400 }, armor: -5, damageDice: { num: 4, sides: 4, bonus: 6 } },
        { level: 23, hpManaDice: { num: 5, sides: 10, bonus: 450 }, armor: -6, damageDice: { num: 3, sides: 6, bonus: 6 } },
        { level: 24, hpManaDice: { num: 5, sides: 10, bonus: 500 }, armor: -6, damageDice: { num: 2, sides: 10, bonus: 6 } },
        { level: 25, hpManaDice: { num: 5, sides: 10, bonus: 550 }, armor: -7, damageDice: { num: 2, sides: 10, bonus: 7 } },
        { level: 26, hpManaDice: { num: 5, sides: 10, bonus: 600 }, armor: -7, damageDice: { num: 3, sides: 7, bonus: 7 } },
        { level: 27, hpManaDice: { num: 5, sides: 10, bonus: 650 }, armor: -8, damageDice: { num: 5, sides: 4, bonus: 7 } },
        { level: 28, hpManaDice: { num: 6, sides: 12, bonus: 703 }, armor: -8, damageDice: { num: 2, sides: 12, bonus: 8 } },
        { level: 29, hpManaDice: { num: 6, sides: 12, bonus: 778 }, armor: -9, damageDice: { num: 2, sides: 12, bonus: 8 } },
        { level: 30, hpManaDice: { num: 6, sides: 12, bonus: 853 }, armor: -9, damageDice: { num: 4, sides: 6, bonus: 8 } },
        { level: 31, hpManaDice: { num: 6, sides: 12, bonus: 928 }, armor: -10, damageDice: { num: 4, sides: 6, bonus: 9 } },
        { level: 32, hpManaDice: { num: 10, sides: 10, bonus: 1000 }, armor: -10, damageDice: { num: 6, sides: 4, bonus: 9 } },
        { level: 33, hpManaDice: { num: 10, sides: 10, bonus: 1100 }, armor: -11, damageDice: { num: 6, sides: 4, bonus: 10 } },
        { level: 34, hpManaDice: { num: 10, sides: 10, bonus: 1200 }, armor: -11, damageDice: { num: 4, sides: 7, bonus: 10 } },
        { level: 35, hpManaDice: { num: 10, sides: 10, bonus: 1300 }, armor: -11, damageDice: { num: 4, sides: 7, bonus: 11 } },
        { level: 36, hpManaDice: { num: 10, sides: 10, bonus: 1400 }, armor: -12, damageDice: { num: 3, sides: 10, bonus: 11 } },
        { level: 37, hpManaDice: { num: 10, sides: 10, bonus: 1500 }, armor: -12, damageDice: { num: 3, sides: 10, bonus: 12 } },
        { level: 38, hpManaDice: { num: 10, sides: 10, bonus: 1600 }, armor: -13, damageDice: { num: 5, sides: 6, bonus: 12 } },
        { level: 39, hpManaDice: { num: 15, sides: 10, bonus: 1700 }, armor: -13, damageDice: { num: 5, sides: 6, bonus: 13 } },
        { level: 40, hpManaDice: { num: 15, sides: 10, bonus: 1850 }, armor: -13, damageDice: { num: 4, sides: 8, bonus: 13 } },
        { level: 41, hpManaDice: { num: 25, sides: 10, bonus: 2000 }, armor: -14, damageDice: { num: 4, sides: 8, bonus: 14 } },
        { level: 42, hpManaDice: { num: 25, sides: 10, bonus: 2250 }, armor: -14, damageDice: { num: 3, sides: 12, bonus: 14 } },
        { level: 43, hpManaDice: { num: 25, sides: 10, bonus: 2500 }, armor: -15, damageDice: { num: 3, sides: 12, bonus: 15 } },
        { level: 44, hpManaDice: { num: 25, sides: 10, bonus: 2750 }, armor: -15, damageDice: { num: 8, sides: 4, bonus: 15 } },
        { level: 45, hpManaDice: { num: 25, sides: 10, bonus: 3000 }, armor: -15, damageDice: { num: 8, sides: 4, bonus: 16 } },
        { level: 46, hpManaDice: { num: 25, sides: 10, bonus: 3250 }, armor: -16, damageDice: { num: 8, sides: 6, bonus: 16 } },
        { level: 47, hpManaDice: { num: 25, sides: 10, bonus: 3500 }, armor: -17, damageDice: { num: 6, sides: 6, bonus: 17 } },
        { level: 48, hpManaDice: { num: 25, sides: 10, bonus: 3750 }, armor: -18, damageDice: { num: 6, sides: 6, bonus: 18 } },
        { level: 49, hpManaDice: { num: 50, sides: 10, bonus: 4000 }, armor: -19, damageDice: { num: 4, sides: 10, bonus: 18 } },
        { level: 50, hpManaDice: { num: 50, sides: 10, bonus: 4500 }, armor: -20, damageDice: { num: 5, sides: 8, bonus: 19 } },
        { level: 51, hpManaDice: { num: 50, sides: 10, bonus: 5000 }, armor: -21, damageDice: { num: 5, sides: 8, bonus: 20 } },
        { level: 52, hpManaDice: { num: 50, sides: 10, bonus: 5500 }, armor: -22, damageDice: { num: 5, sides: 7, bonus: 20 } },
        { level: 53, hpManaDice: { num: 50, sides: 10, bonus: 6000 }, armor: -23, damageDice: { num: 6, sides: 7, bonus: 21 } },
        { level: 54, hpManaDice: { num: 50, sides: 10, bonus: 6500 }, armor: -24, damageDice: { num: 7, sides: 6, bonus: 22 } },
        { level: 55, hpManaDice: { num: 50, sides: 10, bonus: 7000 }, armor: -25, damageDice: { num: 10, sides: 4, bonus: 23 } },
        { level: 56, hpManaDice: { num: 50, sides: 10, bonus: 7500 }, armor: -26, damageDice: { num: 10, sides: 4, bonus: 24 } },
        { level: 57, hpManaDice: { num: 50, sides: 10, bonus: 8000 }, armor: -27, damageDice: { num: 6, sides: 8, bonus: 24 } },
        { level: 58, hpManaDice: { num: 50, sides: 10, bonus: 8500 }, armor: -28, damageDice: { num: 5, sides: 10, bonus: 25 } },
        { level: 59, hpManaDice: { num: 50, sides: 10, bonus: 9000 }, armor: -29, damageDice: { num: 8, sides: 6, bonus: 26 } },
        { level: 60, hpManaDice: { num: 50, sides: 10, bonus: 9500 }, armor: -30, damageDice: { num: 8, sides: 6, bonus: 28 } },
        { level: 61, hpManaDice: { num: 100, sides: 10, bonus: 9500 }, armor: -31, damageDice: { num: 9, sides: 7, bonus: 22 } },
        { level: 62, hpManaDice: { num: 100, sides: 10, bonus: 9750 }, armor: -32, damageDice: { num: 9, sides: 7, bonus: 24 } },
        { level: 63, hpManaDice: { num: 100, sides: 10, bonus: 10000 }, armor: -33, damageDice: { num: 9, sides: 7, bonus: 26 } },
        { level: 64, hpManaDice: { num: 100, sides: 10, bonus: 10125 }, armor: -34, damageDice: { num: 9, sides: 7, bonus: 28 } },
        { level: 65, hpManaDice: { num: 100, sides: 10, bonus: 10250 }, armor: -35, damageDice: { num: 7, sides: 10, bonus: 27 } },
        { level: 66, hpManaDice: { num: 100, sides: 10, bonus: 10375 }, armor: -36, damageDice: { num: 7, sides: 10, bonus: 29 } },
        { level: 67, hpManaDice: { num: 100, sides: 10, bonus: 10500 }, armor: -37, damageDice: { num: 7, sides: 10, bonus: 31 } },
        { level: 68, hpManaDice: { num: 100, sides: 10, bonus: 10625 }, armor: -38, damageDice: { num: 7, sides: 10, bonus: 33 } },
        { level: 69, hpManaDice: { num: 100, sides: 10, bonus: 10750 }, armor: -39, damageDice: { num: 7, sides: 10, bonus: 35 } },
        { level: 70, hpManaDice: { num: 100, sides: 10, bonus: 10875 }, armor: -40, damageDice: { num: 8, sides: 13, bonus: 19 } },
        { level: 71, hpManaDice: { num: 100, sides: 10, bonus: 11000 }, armor: -41, damageDice: { num: 8, sides: 13, bonus: 21 } },
        { level: 72, hpManaDice: { num: 110, sides: 10, bonus: 11000 }, armor: -42, damageDice: { num: 8, sides: 13, bonus: 23 } },
        { level: 73, hpManaDice: { num: 110, sides: 10, bonus: 11125 }, armor: -43, damageDice: { num: 8, sides: 13, bonus: 25 } },
        { level: 74, hpManaDice: { num: 110, sides: 10, bonus: 11250 }, armor: -44, damageDice: { num: 8, sides: 13, bonus: 27 } },
        { level: 75, hpManaDice: { num: 110, sides: 10, bonus: 11375 }, armor: -45, damageDice: { num: 8, sides: 13, bonus: 29 } },
        { level: 76, hpManaDice: { num: 110, sides: 10, bonus: 11500 }, armor: -46, damageDice: { num: 8, sides: 13, bonus: 31 } },
        { level: 77, hpManaDice: { num: 110, sides: 10, bonus: 11625 }, armor: -47, damageDice: { num: 8, sides: 13, bonus: 33 } },
        { level: 78, hpManaDice: { num: 110, sides: 10, bonus: 11750 }, armor: -48, damageDice: { num: 8, sides: 13, bonus: 35 } },
        { level: 79, hpManaDice: { num: 110, sides: 10, bonus: 11875 }, armor: -49, damageDice: { num: 8, sides: 13, bonus: 37 } },
        { level: 80, hpManaDice: { num: 110, sides: 10, bonus: 12000 }, armor: -50, damageDice: { num: 10, sides: 14, bonus: 20 } },
        { level: 81, hpManaDice: { num: 115, sides: 10, bonus: 12000 }, armor: -51, damageDice: { num: 10, sides: 14, bonus: 22 } },
        { level: 82, hpManaDice: { num: 115, sides: 10, bonus: 12125 }, armor: -52, damageDice: { num: 10, sides: 14, bonus: 23 } },
        { level: 83, hpManaDice: { num: 115, sides: 10, bonus: 12250 }, armor: -53, damageDice: { num: 10, sides: 14, bonus: 24 } },
        { level: 84, hpManaDice: { num: 115, sides: 10, bonus: 12375 }, armor: -54, damageDice: { num: 10, sides: 14, bonus: 25 } },
        { level: 85, hpManaDice: { num: 115, sides: 10, bonus: 12500 }, armor: -55, damageDice: { num: 10, sides: 14, bonus: 26 } },
        { level: 86, hpManaDice: { num: 115, sides: 10, bonus: 12625 }, armor: -56, damageDice: { num: 10, sides: 14, bonus: 27 } },
        { level: 87, hpManaDice: { num: 115, sides: 10, bonus: 12750 }, armor: -57, damageDice: { num: 10, sides: 14, bonus: 28 } },
        { level: 88, hpManaDice: { num: 115, sides: 10, bonus: 12875 }, armor: -58, damageDice: { num: 10, sides: 14, bonus: 29 } },
        { level: 89, hpManaDice: { num: 115, sides: 10, bonus: 13000 }, armor: -59, damageDice: { num: 10, sides: 14, bonus: 30 } },
        { level: 90, hpManaDice: { num: 115, sides: 12, bonus: 13000 }, armor: -60, damageDice: { num: 10, sides: 14, bonus: 31 } },
        { level: 91, hpManaDice: { num: 115, sides: 12, bonus: 13125 }, armor: -61, damageDice: { num: 12, sides: 13, bonus: 20 } },
        { level: 92, hpManaDice: { num: 115, sides: 12, bonus: 13250 }, armor: -61, damageDice: { num: 12, sides: 13, bonus: 21 } },
        { level: 93, hpManaDice: { num: 115, sides: 12, bonus: 13375 }, armor: -62, damageDice: { num: 12, sides: 13, bonus: 22 } },
        { level: 94, hpManaDice: { num: 115, sides: 12, bonus: 13500 }, armor: -62, damageDice: { num: 12, sides: 13, bonus: 23 } },
        { level: 95, hpManaDice: { num: 115, sides: 12, bonus: 13625 }, armor: -63, damageDice: { num: 12, sides: 13, bonus: 24 } },
        { level: 96, hpManaDice: { num: 115, sides: 12, bonus: 13750 }, armor: -63, damageDice: { num: 12, sides: 13, bonus: 25 } },
        { level: 97, hpManaDice: { num: 115, sides: 12, bonus: 13875 }, armor: -64, damageDice: { num: 12, sides: 13, bonus: 26 } },
        { level: 98, hpManaDice: { num: 115, sides: 12, bonus: 14000 }, armor: -64, damageDice: { num: 12, sides: 13, bonus: 27 } },
        { level: 99, hpManaDice: { num: 115, sides: 15, bonus: 14000 }, armor: -65, damageDice: { num: 12, sides: 13, bonus: 28 } },
        { level: 100, hpManaDice: { num: 115, sides: 15, bonus: 14125 }, armor: -65, damageDice: { num: 12, sides: 13, bonus: 29 } },
        { level: 101, hpManaDice: { num: 115, sides: 15, bonus: 14250 }, armor: -66, damageDice: { num: 12, sides: 13, bonus: 30 } },
        { level: 102, hpManaDice: { num: 115, sides: 15, bonus: 14375 }, armor: -66, damageDice: { num: 12, sides: 13, bonus: 31 } },
        { level: 103, hpManaDice: { num: 115, sides: 15, bonus: 14500 }, armor: -67, damageDice: { num: 15, sides: 12, bonus: 22 } },
        { level: 104, hpManaDice: { num: 115, sides: 15, bonus: 14625 }, armor: -67, damageDice: { num: 15, sides: 12, bonus: 23 } },
        { level: 105, hpManaDice: { num: 115, sides: 15, bonus: 14750 }, armor: -68, damageDice: { num: 15, sides: 12, bonus: 24 } },
        { level: 106, hpManaDice: { num: 115, sides: 15, bonus: 15000 }, armor: -68, damageDice: { num: 15, sides: 12, bonus: 25 } },
        { level: 107, hpManaDice: { num: 115, sides: 15, bonus: 15250 }, armor: -69, damageDice: { num: 15, sides: 12, bonus: 26 } },
        { level: 108, hpManaDice: { num: 115, sides: 15, bonus: 15500 }, armor: -69, damageDice: { num: 15, sides: 12, bonus: 27 } },
        { level: 109, hpManaDice: { num: 115, sides: 15, bonus: 15750 }, armor: -70, damageDice: { num: 15, sides: 12, bonus: 28 } },
        { level: 110, hpManaDice: { num: 115, sides: 15, bonus: 16000 }, armor: -70, damageDice: { num: 15, sides: 12, bonus: 29 } },
        { level: 111, hpManaDice: { num: 115, sides: 20, bonus: 16000 }, armor: -71, damageDice: { num: 15, sides: 12, bonus: 30 } },
        { level: 112, hpManaDice: { num: 115, sides: 20, bonus: 16125 }, armor: -71, damageDice: { num: 15, sides: 12, bonus: 31 } },
        { level: 113, hpManaDice: { num: 115, sides: 20, bonus: 16250 }, armor: -72, damageDice: { num: 15, sides: 12, bonus: 32 } },
        { level: 114, hpManaDice: { num: 115, sides: 20, bonus: 16375 }, armor: -72, damageDice: { num: 20, sides: 10, bonus: 25 } },
        { level: 115, hpManaDice: { num: 115, sides: 20, bonus: 16500 }, armor: -73, damageDice: { num: 20, sides: 10, bonus: 27 } },
        { level: 116, hpManaDice: { num: 115, sides: 20, bonus: 16625 }, armor: -73, damageDice: { num: 20, sides: 10, bonus: 29 } },
        { level: 117, hpManaDice: { num: 115, sides: 20, bonus: 16750 }, armor: -74, damageDice: { num: 20, sides: 10, bonus: 31 } },
        { level: 118, hpManaDice: { num: 115, sides: 20, bonus: 16875 }, armor: -74, damageDice: { num: 20, sides: 10, bonus: 33 } },
        { level: 119, hpManaDice: { num: 115, sides: 20, bonus: 17000 }, armor: -75, damageDice: { num: 20, sides: 10, bonus: 35 } },
        { level: 120, hpManaDice: { num: 120, sides: 24, bonus: 17000 }, armor: -75, damageDice: { num: 20, sides: 10, bonus: 37 } }
    ],

    // Lista de materiales disponibles para objetos.
    // Utilizada para sugerencias en el campo de material de objetos.
    materials: [
        'acero',
        'ácido',
        'adamantita',
        'aire',
        'alambre',
        'arenisca',
        'arcilla',
        'agua',
        'bálsamo',
        'bambú',
        'baba',
        'bronce',
        'carbón',
        'cartón',
        'cáñamo',
        'carne',
        'ceniza',
        'cerámica',
        'cera',
        'comida',
        'concha',
        'cobre',
        'coral',
        'corcho',
        'corindón',
        'crema',
        'cristal',
        'cuarzo',
        'cuero de cabrito',
        'cuero duro/blando',
        'cuerno',
        'diamante',
        'ébano',
        'electrum',
        'esmalte',
        'encaje',
        'energía',
        'escama de dragón',
        'escama de dragón azul',
        'escama de dragón negro',
        'escama de dragón blanco',
        'escama de dragón rojo',
        'esponja',
        'estaño',
        'etereidad',
        'fieltro',
        'fuego',
        'gelatina',
        'goma',
        'granito',
        'hielo',
        'hierro',
        'hueso',
        'laen claro',
        'laen oscuro',
        'lana',
        'latón',
        'lino',
        'lona',
        'madera',
        'madera dura',
        'madera blanda',
        'magnetita',
        'mármol',
        'marfil',
        'metal',
        'mithril',
        'ninguno',
        'obsidiana',
        'oro',
        'pan',
        'papel',
        'pergamino',
        'peltre',
        'piel',
        'piel de serpiente',
        'piedra',
        'plumas',
        'plástico',
        'plata',
        'platino',
        'plomo',
        'porcelana',
        'satén',
        'seda elástica',
        'sílex',
        'tela',
        'telaraña',
        'terciopelo',
        'tierra',
        'tripa',
        'vidrio',
        'vitela',
        'presión',
        'escurridizo',
        'legendario',
        'delicado',
        'antidenso',
        'denso'
    ],

    // Lista de especiales disponibles para la sección #SPECIALS.
    // Cada objeto incluye su nombre y una breve descripción usada en los tooltips.
    specials: [
        { value: 'spec_troll_member', descripcion: 'Troll que ataca a los ogros cercanos.' },
        { value: 'spec_ogre_member', descripcion: 'Ogro que ataca a los trolls cercanos.' },
        { value: 'spec_patrolman', descripcion: 'Patrullero que interrumpe peleas y sopla un silbato.' },
        { value: 'spec_nasty', descripcion: 'Ladrón agresivo que roba oro y huye.' },
        { value: 'spec_breath_any', descripcion: 'Dragón con aliento elemental aleatorio.' },
        { value: 'spec_cast_adepto', descripcion: 'NPC que lanza hechizos beneficiosos a novatos.' },
        { value: 'spec_cast_clerigo', descripcion: 'Clérigo que lanza hechizos ofensivos.' },
        { value: 'spec_cast_mago', descripcion: 'Mago que lanza hechizos ofensivos.' },
        { value: 'spec_fido', descripcion: 'Carroñero que devora cadáveres de NPCs.' },
        { value: 'spec_guard', descripcion: 'Guardia que ataca criminales y defiende inocentes.' },
        { value: 'spec_janitor', descripcion: 'Conserje que recoge basura y objetos baratos.' },
        { value: 'spec_alcalde', descripcion: 'NPC que sigue una rutina diaria de alcalde.' },
        { value: 'spec_veneno', descripcion: 'Envenenador que lanza el hechizo veneno.' },
        { value: 'spec_ladron', descripcion: 'Ladrón que roba dinero a los jugadores.' },
        { value: 'spec_cast_runk', descripcion: 'Hechicero con conjuros propios de Runk.' },
        { value: 'spec_cast_oteren', descripcion: 'Hechicero con conjuros propios de Oteren.' },
        { value: 'spec_guardia_malo', descripcion: 'Guardia que protege a personajes malvados.' },
        { value: 'spec_guardia_bueno', descripcion: 'Guardia que protege a personajes buenos.' },
        { value: 'spec_teleporter', descripcion: 'NPC que se teletransporta periódicamente.' },
        { value: 'spec_barco', descripcion: 'NPC que simula ser un barco entre áreas.' },
        { value: 'spec_esfinge', descripcion: 'Guardiana mística que controla el acceso por clan.' },
        { value: 'spec_guardia_clan', descripcion: 'Guardia que defiende un clan y ataca intrusos.' },
        { value: 'spec_entrenador_especial', descripcion: 'Entrenador que inicia cadenas de misiones.' },
        { value: 'spec_quest_especial_1', descripcion: 'NPC guía de un quest con recompensas.' },
        { value: 'spec_quest_especial_2', descripcion: 'NPC complementario del quest narrativo.' },
        { value: 'spec_secretario', descripcion: 'Controla acceso al señor según ranking PK.' },
        { value: 'spec_mordisco', descripcion: 'Criatura que muerde y asesina a jugadores débiles.' },
        { value: 'spec_entrenador_samurai', descripcion: 'Entrenador de samuráis con misiones especiales.' },
        { value: 'spec_samu_experto_1', descripcion: 'Experto samurái que entrega misiones iniciales.' },
        { value: 'spec_samu_experto_2', descripcion: 'Experto samurái avanzado con combates duros.' }
    ],

    // Lista de tipos de objetos disponibles.
    // "label" se muestra en la UI (español) y "value" se escribe en el archivo .are (inglés).
    objectTypes: [
        { value: 'weapon', label: 'arma' },
        { value: 'boat', label: 'barco' },
        { value: 'staff', label: 'bastón' },
        { value: 'trash', label: 'basura' },
        { value: 'npc_corpse', label: 'cadáver NPC' },
        { value: 'object_corpse', label: 'cadáver objeto' },
        { value: 'pc_corpse', label: 'cadáver PJ' },
        { value: 'food', label: 'comida' },
        { value: 'food_buff', label: 'comida con buff' },
        { value: 'container', label: 'contenedor' },
        { value: 'drink', label: 'contenedor de bebida' },
        { value: 'money', label: 'dinero' },
        { value: 'disfraz', label: 'disfraz' },
        { value: 'emblema', label: 'emblema' },
        { value: 'fountain', label: 'fuente' },
        { value: 'gem', label: 'gema' },
        { value: 'jukebox', label: 'gramola' },
        { value: 'jewelry', label: 'joyería' },
        { value: 'key', label: 'llave' },
        { value: 'room_key', label: 'llave de habitación' },
        { value: 'light', label: 'luz' },
        { value: 'map', label: 'mapa' },
        { value: 'furniture', label: 'mueble' },
        // { value: 'pala', label: 'pala' },
        // { value: 'pico', label: 'pico' },
        // { value: 'mineral', label: 'mineral' },
        // { value: 'ore', label: 'ore' },
        { value: 'scroll', label: 'pergamino' },
        { value: 'warp_stone', label: 'piedra de portal y nexus' },
        { value: 'pill', label: 'píldora' },
        { value: 'potion', label: 'poción' },
        { value: 'portal', label: 'portal' },
        { value: 'proteccion', label: 'protección' },
        { value: 'protect', label: 'proteger' },
        { value: 'clothing', label: 'ropa' },
        { value: 'tesoro', label: 'tesoro' },
        { value: 'wand', label: 'varita' }
    ],


    // Etiquetas para los valores V0-V4 de objetos, según su tipo.
    objectValueLabels: {
        'weapon': ['Tipo de arma', 'Número de dados', 'Cara de dados', 'Tipo de daño', 'Flags de arma'],
        'boat': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'staff': ['nivel de hechizo', 'cargas máximas', 'cargas actuales', 'hechizo', 'CONFIGURAR A 0'],
        'trash': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'npc_corpse': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'object_corpse': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'pc_corpse': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'food': ['hours full', 'hour hung', 'CONFIGURAR A 0', '0/A=pois', 'CONFIGURAR A 0'],
        'food_buff': ['duracion', 'Cantidad', 'apply', 'A/I/R/V', 'flags/A=veneno'],
        'container': ['Maximo peso', 'Flags', 'Vnum de la llave', 'Objetos maximos dentro', 'Multiplicador de peso'], // Assuming 'containers'
        'drink': ['capacidad máxima', 'capacidad actual', 'líquido', 'veneno', 'CONFIGURAR A 0'], // Assuming 'drink' is 'drink containers'
        'money': ['plata', 'oro', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'disfraz': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'emblema': ['id_clan', 'rango', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'], // Adjusted for 5 values, empty for unused
        'fountain': ['CONFIGURAR A -1', 'CONFIGURAR A -1', 'líquido', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'gem': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'jukebox': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'jewelry': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'key': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'room_key': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'light': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'duración de luz', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'map': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'furniture': ['gente', 'total wei', 'fur flags', 'heal bon', 'mana bon'],
        // 'pala': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        // 'pico': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        // 'mineral': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        // 'ore': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'scroll': ['nivel de hechizo', 'hechizo', 'hechizo', 'hechizo', 'hechizo'],
        'warp_stone': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'pill': ['nivel de hechizo', 'hechizo', 'hechizo', 'hechizo', 'hechizo'],
        'potion': ['nivel de hechizo', 'hechizo', 'hechizo', 'hechizo', 'hechizo'],
        'portal': ['cargas', 'exit flags', 'gate flags', 'Vnum Room', 'CONFIGURAR A 0'], // Assuming 'portals'
        'proteccion': ['perforar', 'golpear', 'cortar', 'exótico', 'volumen'],
        'protect': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'clothing': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'tesoro': ['CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0', 'CONFIGURAR A 0'],
        'wand': ['nivel de hechizo', 'cargas máximas', 'cargas actuales', 'hechizo', 'CONFIGURAR A 0'],
        'default': ['Valor 0', 'Valor 1', 'Valor 2', 'Valor 3', 'Valor 4'] // Default for types not explicitly listed
    },

    // Opciones desplegables para los valores V0-V4 según el tipo de objeto.
    // Si un V específico no está definido para un tipo, se usará "0" por defecto.
    objectValueOptions: {
        weapon: {
            v0: [
                'espada', 'daga', 'boleadoras', 'maza',
                'hacha', 'mayal', 'latigo', 'lanza'
            ],
            v3: [
                { value: 'beating', label: 'azote' },
                { value: 'peckb', label: 'besito de hierro' },
                { value: 'slap', label: 'bofetón' },
                { value: 'crush', label: 'cabezazo' },
                { value: 'smash', label: 'choque' },
                { value: 'chomp', label: 'chomp' },
                { value: 'flbite', label: 'chorro de fuego' },
                { value: 'chomp', label: 'chomp' },
                { value: 'slice', label: 'tajo' },
                { value: 'chop', label: 'tajo devastador' },
                { value: 'slash', label: 'golpe de espada' },
                { value: 'cleave', label: 'golpe carnicero' },
                { value: 'wrath', label: 'golpe furioso' },
                { value: 'frbite', label: 'golpe helador' },
                { value: 'acbite', label: 'golpe ácido' },
                { value: 'divine', label: 'poder divino' },
                { value: 'thrust', label: 'empujón' },
                { value: 'pierce', label: 'perforar' },
                { value: 'peck', label: 'picotazo' },
                { value: 'punch', label: 'Puñetazo' },
                { value: 'pound', label: 'porrazo' },
                { value: 'shbite', label: 'relámpago luminoso' },
                { value: 'drain', label: 'pase de succión vital' },
                { value: 'grep', label: 'estoque' },
                { value: 'bite', label: 'mordisco' },
                { value: 'flame', label: 'llamarazo' },
                { value: 'magic', label: 'mágico pase' },
                { value: 'sting', label: 'ataque "picadura de avispa"' },
                { value: 'thwack', label: 'Plaff!' },
                { value: 'slime', label: 'salivazo' },
                { value: 'shock', label: 'shock' },
                { value: 'charge', label: 'barrigazo' },
                { value: 'claw', label: 'gancho' },
                { value: 'latigo', label: 'latigazo' },
                { value: 'stab', label: 'pinchazo' },
                { value: 'blast', label: 'mazazo' },
                { value: 'scratch', label: 'zarcalmao ursido' },
                { value: 'digestion', label: 'vomito acido' },
                { value: 'chill', label: 'pinchazo frío' }
            ],
            v4: [
                { value: '0', label: 'Nada' },
                { value: 'A', label: 'flaming' },
                { value: 'B', label: 'frost' },
                { value: 'C', label: 'vampiric' },
                { value: 'D', label: 'sharp' },
                { value: 'E', label: 'vorpal' },
                { value: 'F', label: 'two-handed' },
                { value: 'G', label: 'shocking' },
                { value: 'H', label: 'poisoned' },
                { value: 'I', label: 'Sangriento' },
                { value: 'J', label: 'Hemorragia' }
            ]
        },


        boat: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        staff: {
            v3: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        trash: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        npc_corpse: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },
        object_corpse: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        pc_corpse: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        food: {
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [
                { value: '0', label: 'No venenoso' },
                { value: 'A', label: 'Envenenado' }
            ],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        food_buff: {
            v2: [
                { value: '0', label: 'Ninguno' },
                { value: '1', label: 'Fuerza' },
                { value: '2', label: 'Destreza' },
                { value: '3', label: 'Inteligencia' },
                { value: '4', label: 'Sabiduría' },
                { value: '5', label: 'Constitución' },
                { value: '6', label: 'Sexo' },
                { value: '7', label: 'Clase' },
                { value: '8', label: 'Nivel' },
                { value: '9', label: 'Edad' },
                { value: '10', label: 'Altura' },
                { value: '11', label: 'Peso' },
                { value: '12', label: 'Maná' },
                { value: '13', label: 'Puntos de golpe' },
                { value: '14', label: 'Movimiento' },
                { value: '15', label: 'Oro' },
                { value: '16', label: 'Experiencia' },
                { value: '17', label: 'Clase de armadura (CA)' },
                { value: '18', label: 'Hitroll' },
                { value: '19', label: 'Damroll' },
                { value: '20', label: 'Hechizo (incluye varas y báculos)' },
                { value: '21', label: 'Salvación vs Vara' },
                { value: '22', label: 'Salvación vs Petrificar' },
                { value: '23', label: 'Salvación vs Aliento' },
                { value: '24', label: 'Salvación vs Hechizo' },
                { value: '25', label: 'Afecto de hechizo' },
                { value: '26', label: 'Poder de hechizo' },
                { value: '27', label: 'Poder de curación' }
            ],
            v3: [
                { value: '0', label: 'NADA' },
                { value: 'A', label: 'Afecta' },
                { value: 'I', label: 'Inmune' },
                { value: 'R', label: 'Resistencia' },
                { value: 'V', label: 'Vulnerabilidad' }
            ],
            v4: [
                { value: '0', label: 'NADA' },
                { value: 'A', label: 'Blind' },
                { value: 'B', label: 'Invisible' },
                { value: 'C', label: 'Detect_evil' },
                { value: 'D', label: 'Detect_invis' },
                { value: 'E', label: 'Detect_magic' },
                { value: 'F', label: 'Detect_hidden' },
                { value: 'G', label: 'Detect_good' },
                { value: 'H', label: 'Sanctuary' },
                { value: 'I', label: 'Faerie_fire' },
                { value: 'J', label: 'Infrared' },
                { value: 'K', label: 'Curse' },
                { value: 'L', label: 'Flaming (No implementado)' },
                { value: 'M', label: 'Poisoned' },
                { value: 'N', label: 'Prot_evil' },
                { value: 'O', label: 'Prot_good' },
                { value: 'P', label: 'Sneak' },
                { value: 'Q', label: 'Hide' },
                { value: 'R', label: 'Sleep' },
                { value: 'S', label: 'Charm' },
                { value: 'T', label: 'Flying' },
                { value: 'U', label: 'Pass_door' },
                { value: 'V', label: 'Haste' },
                { value: 'W', label: 'Calm' },
                { value: 'X', label: 'Plague' },
                { value: 'Y', label: 'Weaken' },
                { value: 'Z', label: 'Dark_vis' },
                { value: 'a', label: 'Berserk (No implementado)' },
                { value: 'b', label: 'Swim (No implementado)' },
                { value: 'c', label: 'Regen' },
                { value: 'd', label: 'Slow' }
            ]
        },

        container: {

        },

        drink: {
            v2: [
                { value: 'vino_tinto', label: 'Vino Tinto' },
                { value: 'licor_de_monjes', label: 'Licor de Monjes' },
                { value: 'aguardiente', label: 'Aguardiente' },
                { value: 'zumo_de_sandia', label: 'Zumo de Sandía' },
                { value: 'agua_de_mar', label: 'Agua de Mar' },
                { value: 'ron', label: 'Ron' },
                { value: 'vino_blanco', label: 'Vino Blanco' },
                { value: 'vino_rosado', label: 'Vino Rosado' },
                { value: 'licor_benedictino', label: 'Licor Benedictino' },
                { value: 'zumo_de_higos', label: 'Zumo de Higos' },
                { value: 'agua', label: 'Agua' },
                { value: 'brandy', label: 'Brandy' },
                { value: 'cerveza', label: 'Cerveza' },
                { value: 'whisky', label: 'Whisky' },
                { value: 'leche', label: 'Leche' },
                { value: 'te', label: 'Té' },
                { value: 'tila', label: 'Tila' },
                { value: 'cava', label: 'Cava' },
                { value: 'limonada', label: 'Limonada' },
                { value: 'vinito_de_midgaard', label: 'Vinito de Midgaard' },
                { value: 'absenta', label: 'Absenta' },
                { value: 'cerveza_negra', label: 'Cerveza Negra' },
                { value: 'amontillado', label: 'Amontillado' },
                { value: 'agua_de_acequia', label: 'Agua de Acequia' },
                { value: 'chupitos_de_borrachin', label: 'Chupitos de Borrachín' },
                { value: 'zumo_de_naranja', label: 'Zumo de Naranja' },
                { value: 'cordial', label: 'Cordial' },
                { value: 'vinagre', label: 'Vinagre' },
                { value: 'sherry', label: 'Sherry' },
                { value: 'sorbete_medieval', label: 'Sorbete Medieval' },
                { value: 'licor_de_cactus', label: 'Licor de Cactus' },
                { value: 'vodka', label: 'Vodka' },
                { value: 'hidromiel', label: 'Hidromiel' }
            ],
            v3: [
                { value: '0', label: 'No envenenando' },
                { value: '1', label: 'envenenando' }
            ],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        money: {
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        disfraz: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        emblema: {
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        fountain: {
            v0: [{ value: '-1', label: 'Siempre es -1' }],
            v1: [{ value: '-1', label: 'Siempre es -1' }],
            v2: [
                { value: 'vino_tinto', label: 'Vino Tinto' },
                { value: 'licor_de_monjes', label: 'Licor de Monjes' },
                { value: 'aguardiente', label: 'Aguardiente' },
                { value: 'zumo_de_sandia', label: 'Zumo de Sandía' },
                { value: 'agua_de_mar', label: 'Agua de Mar' },
                { value: 'ron', label: 'Ron' },
                { value: 'vino_blanco', label: 'Vino Blanco' },
                { value: 'vino_rosado', label: 'Vino Rosado' },
                { value: 'licor_benedictino', label: 'Licor Benedictino' },
                { value: 'zumo_de_higos', label: 'Zumo de Higos' },
                { value: 'agua', label: 'Agua' },
                { value: 'brandy', label: 'Brandy' },
                { value: 'cerveza', label: 'Cerveza' },
                { value: 'whisky', label: 'Whisky' },
                { value: 'leche', label: 'Leche' },
                { value: 'te', label: 'Té' },
                { value: 'tila', label: 'Tila' },
                { value: 'cava', label: 'Cava' },
                { value: 'limonada', label: 'Limonada' },
                { value: 'vinito_de_midgaard', label: 'Vinito de Midgaard' },
                { value: 'absenta', label: 'Absenta' },
                { value: 'cerveza_negra', label: 'Cerveza Negra' },
                { value: 'amontillado', label: 'Amontillado' },
                { value: 'agua_de_acequia', label: 'Agua de Acequia' },
                { value: 'chupitos_de_borrachin', label: 'Chupitos de Borrachín' },
                { value: 'zumo_de_naranja', label: 'Zumo de Naranja' },
                { value: 'cordial', label: 'Cordial' },
                { value: 'vinagre', label: 'Vinagre' },
                { value: 'sherry', label: 'Sherry' },
                { value: 'sorbete_medieval', label: 'Sorbete Medieval' },
                { value: 'licor_de_cactus', label: 'Licor de Cactus' },
                { value: 'vodka', label: 'Vodka' },
                { value: 'hidromiel', label: 'Hidromiel' }
            ],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        gem: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        jukebox: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        jewelry: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        key: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        room_key: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        light: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        map: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        furniture: {

        },

        // pala: {},
        // pico: {},
        // mineral: {},
        // ore: {},

        scroll: {
            v1: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v2: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v3: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v4: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ]
        },

        warp_stone: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        pill: {
            v1: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v2: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v3: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v4: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ]
        },

        potion: {
            v1: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v2: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v3: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v4: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ]
        },

        portal: {
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        proteccion: {

        },

        protect: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        clothing: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        treasure: {
            v0: [{ value: '0', label: 'Siempre es 0' }],
            v1: [{ value: '0', label: 'Siempre es 0' }],
            v2: [{ value: '0', label: 'Siempre es 0' }],
            v3: [{ value: '0', label: 'Siempre es 0' }],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        },

        wand: {

            v3: [
                '\'abrasar\'', '\'acelerar\'', '\'alineacion\'', '\'aliento acido\'',
                '\'aliento fogoso\'', '\'aliento gaseoso\'', '\'aliento helado\'', '\'aliento tormentoso\'',
                '\'antifuego\'', '\'bendecir\'', '\'bendita niebla\'', '\'buen aura\'',
                '\'calma\'', '\'cancelacion\'', '\'causar critico\'', '\'causar leve\'',
                '\'causar serio\'', '\'chupar energia\'', '\'clarividencia\'', '\'compuerta\'',
                '\'control tiempo\'', '\'crear agua\'', '\'crear comida\'', '\'crear fuente\'',
                '\'crear rosa\'', '\'curar critico\'', '\'curar deslumbrar\'', '\'curar enfermo\'',
                '\'curar leve\'', '\'curar serio\'', '\'curar veneno\'', '\'demonfuego\'',
                '\'detectar bondad\'', '\'detectar magia\'', '\'detectar mal\'', '\'detectar oculto\'',
                '\'detectar veneno\'', '\'detectar invisibilidad\'', '\'delirar\'', '\'disco volador\'',
                '\'divina palabra\'', '\'dormir\'', '\'eliminar maldecir\'', '\'encantar arma\'',
                '\'encantar equipo\'', '\'encantar gente\'', '\'escudo\'', '\'fuerza colosal\'',
                '\'gatovision\'', '\'golpear acido\'', '\'golpe de agarre\'', '\'identificar\'',
                '\'invisibilidad\'', '\'lanzar rayo\'', '\'luz continua\'', '\'maldecir\'',
                '\'metal rojo\'', '\'meteorito\'', '\'misil magico\'', '\'nexus\'',
                '\'operacion sexual\'', '\'palabras de regresar\'', '\'piel de piedra\'', '\'plaga\'',
                '\'porrazo\'', '\'portal\'', '\'proteccion\'', '\'proteccion divina\'',
                '\'proteccion infernal\'', '\'rayo de sinceridad\'', '\'rayo letal\'', '\'rayo poderoso\'',
                '\'recargar\'', '\'refrescar\'', '\'relenti\'', '\'reserved\'',
                '\'sanar\'', '\'santuario\'', '\'spray\'', '\'summon\'',
                '\'teleportar\'', '\'terremoto\'', '\'todo curacion\'', '\'todo invisibilidad\'',
                '\'toque ardiente\'', '\'toque frio\'', '\'traspasar\'', '\'ventrilocuo\'',
                '\'veneno\'', '\'volar\''
            ],
            v4: [{ value: '0', label: 'Siempre es 0' }]
        }
    },

    affectBitOptions: {
        A: [
            { value: 'A', label: 'Blind' },
            { value: 'B', label: 'Invisible' },
            { value: 'C', label: 'Detect_evil' },
            { value: 'D', label: 'Detect_invis' },
            { value: 'E', label: 'Detect_magic' },
            { value: 'F', label: 'Detect_hidden' },
            { value: 'G', label: 'Detect_good' },
            { value: 'H', label: 'Sanctuary' },
            { value: 'I', label: 'Faerie_fire' },
            { value: 'J', label: 'Infrared' },
            { value: 'K', label: 'Curse' },
            { value: 'L', label: 'Flaming (No Implementado)' },
            { value: 'M', label: 'Poisoned' },
            { value: 'N', label: 'Prot_evil' },
            { value: 'O', label: 'Prot_good' },
            { value: 'P', label: 'Sneak' },
            { value: 'Q', label: 'Hide' },
            { value: 'R', label: 'Sleep' },
            { value: 'S', label: 'Charm' },
            { value: 'T', label: 'Flying' },
            { value: 'U', label: 'Pass_door' },
            { value: 'V', label: 'Haste' },
            { value: 'W', label: 'Calm' },
            { value: 'X', label: 'Plague' },
            { value: 'Y', label: 'Weaken' },
            { value: 'Z', label: 'Dark_vis' },
            { value: 'a', label: 'Berserk (No Implementado)' },
            { value: 'b', label: 'Swim (No Implementado)' },
            { value: 'c', label: 'Regen' },
            { value: 'd', label: 'Slow' }
        ],
        I: affectIRVBits,
        R: affectIRVBits,
        V: affectIRVBits
    },

    resetDirections: [
        { value: '0', label: 'Norte' },
        { value: '1', label: 'Este' },
        { value: '2', label: 'Sur' },
        { value: '3', label: 'Oeste' },
        { value: '4', label: 'Arriba' },
        { value: '5', label: 'Abajo' },
        { value: '6', label: 'Noreste' },
        { value: '7', label: 'Noroeste' },
        { value: '8', label: 'Sureste' },
        { value: '9', label: 'Suroeste' }
    ],

    resetDoorStates: [
        { value: '0', label: 'Abierta' },
        { value: '1', label: 'Cerrada' },
        { value: '2', label: 'Con llave' }
    ],

    resetWearLocations: [
        { value: '-1', label: 'No vestir' },
        { value: '0', label: 'Luz' },
        { value: '1', label: 'Dedo izquierdo' },
        { value: '2', label: 'Dedo derecho' },
        { value: '3', label: 'Cuello (1)' },
        { value: '4', label: 'Cuello (2)' },
        { value: '5', label: 'En el torso' },
        { value: '6', label: 'Cabeza' },
        { value: '7', label: 'Piernas' },
        { value: '8', label: 'Pies' },
        { value: '9', label: 'Manos' },
        { value: '10', label: 'Brazos' },
        { value: '11', label: 'Escudo' },
        { value: '12', label: 'En la espalda' },
        { value: '13', label: 'Cintura' },
        { value: '14', label: 'Muñeca izquierda' },
        { value: '15', label: 'Muñeca derecha' },
        { value: '16', label: 'Blandido' },
        { value: '17', label: 'Sujeto' },
        { value: '18', label: 'Flotando' },
        { value: '19', label: 'Arma secundaria' },
        { value: '20', label: 'Rodela' },
        { value: '21', label: 'Piernas traseras (centauro)' },
        { value: '22', label: 'Pies traseros (centauro)' },
        { value: '23', label: 'Emblema de clan' }
    ],

    resetMazeClasses: [
        { value: '4', label: 'Cardinales' },
        { value: '6', label: 'Cardinales + arriba/abajo' },
        { value: '10', label: 'Cardinales + arriba/abajo + diagonales' }
    ],

    shopObjectTypes: [
        { value: '1', label: 'Luz' },
        { value: '2', label: 'Pergamino' },
        { value: '3', label: 'Varita' },
        { value: '4', label: 'Bastón' },
        { value: '5', label: 'Arma' },
        { value: '8', label: 'Tesoro' },
        { value: '9', label: 'Armadura' },
        { value: '10', label: 'Poción' },
        { value: '12', label: 'Muebles' },
        { value: '13', label: 'Basura' },
        { value: '15', label: 'Contenedor' },
        { value: '17', label: 'Contenedor de bebida' },
        { value: '18', label: 'Llave' },
        { value: '19', label: 'Comida' },
        { value: '22', label: 'Barco' },
        { value: '26', label: 'Píldora' },
        { value: '28', label: 'Mapa' },
        { value: '29', label: 'Portal' },
        { value: '30', label: 'Piedra de teletransporte' },
        { value: '32', label: 'Gema' },
        { value: '33', label: 'Joyería' }
    ],

    shopProfitOptions: Array.from({ length: 201 }, (_, i) => ({ value: String(i), label: String(i) })),

    shopHours: Array.from({ length: 24 }, (_, i) => ({ value: String(i), label: String(i) })),

    // Prompts detallados para la generación de descripciones de IA.
    // Cada clave representa un tipo de entidad (mob, object, room) y contiene sub-prompts específicos.
    aiPrompts: {
        mob: {
            shortLongLook: "Basado en la siguiente idea: ${promptText}, genera UN ÚNICO objeto JSON con tres descripciones para un PNJ (mob) de un juego MUD, no puede haber más de UN ÚNICO objeto JSON. Las descripciones deben seguir estas reglas:\n\n\"short_desc\": Descripción super breve (máximo 20 caracteres). Si es un mob genérico (barrendero, perro, guardia), usa el artículo: \"El barrendero\", \"El perro\", \"El guardia\", \"La tendera\". Si el mob tiene un nombre propio, no uses artículo: \"Arturo\", \"Cleopatra\", \"Thor\".\n\n\"long_desc\": No muy extensa. Nombra al mob y describe lo que está haciendo o una característica clave. Ejemplos: \"Un troll de piedra con una sonrisa pétrea.\", \"Arturo está sentado en el suelo afilando la espada.\", \"El asesino acecha en las sombras.\"\n\n\"look_desc\": Extensa y muy descriptiva, no mas de 200 palabras a no ser que se especifique lo contrario. Describe profundamente el mob, sus detalles, apariencia, etc.\n\nResponde solo con el objeto JSON, sin texto adicional ni markdown."
        },
        object: {
            shortLong: "Basado en la siguiente idea: ${promptText}, genera UN ÚNICO objeto JSON con la descripción para un objeto de un juego MUD. Las descripciones deben seguir estas reglas:\n\n\"short_desc\": Descripción muy breve (máximo 10 palabras). Es la que se usa en el inventario. Ejemplos: \"un anillo de oro\", \"la espada excalibur\", \"un zurrón lleno de remaches\".\n\n\"long_desc\": No muy extensa. Es la que se ve cuando llegas a la sala. Nombra al objeto y describe lo que está haciendo o una característica clave. Ejemplos: \"Una llave con el anagrama del Hotel Renedo y una pequeña inscripción.\", \"Un cofre de madera reposa en el centro de la sala.\"\n\nResponde solo con el objeto JSON, sin texto adicional ni markdown.",
            extra: "Basado en la siguiente idea: ${promptText}, genera UN ÚNICO objeto JSON con una descripción extra para un objeto de un juego MUD. Esta descripción debe ser muy descriptiva sin ser extremadamente larga no mas de 200 palabras a no ser que se especifique lo contrario., similar a la descripción al mirar de un mob, detallando el objeto, su apariencia, historia, etc. Responde solo con el objeto JSON, usando la clave \"extra_desc\"."
        },
        room: {
            description: "Basado en la siguiente idea: ${promptText}, genera UN ÚNICO objeto JSON con una descripción para una habitación de un juego MUD. Esta descripción debe ser extensa y muy descriptiva aunque no mas de 200 palabras a no ser que se especifique lo contrario., detallando el ambiente, objetos, sonidos, olores, etc. Responde solo con el objeto JSON, usando la clave \"room_desc\".",
            extra: "Basado en la siguiente idea: ${promptText}, genera UN ÚNICO objeto JSON con una descripción extra para una habitación de un juego MUD. Esta descripción debe ser muy descriptiva sin ser extremadamente larga no mas de 200 palabras a no ser que se especifique lo contrario., detallando el ambiente, su historia u otros elementos relevantes. Puede que la descripción extra sea la descripción de algo en la habitación ejemplos: \"una placa\" \"una columna\" etc. Responde solo con el objeto JSON, usando la clave \"extra_desc\"."
        }
    }
    // Aquí se pueden añadir futuras listas (materiales, tipos de armas, etc.)
};
